backend:
  name: github
  repo: coreyAdams1970/kick_it_up_a_notch
  branch: main

  media_library:
    name: cloudinary
    config:
      cloud_name: dlfhllrti
      api_key: 248873222392649

media_folder: content/assets
public_folder: ../assets
logo_url: https://kickitupdesertdesign/images/logo.png

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
